### ISSUE TITLE
Blockchain.info payload starts with AAAAAAAAAAAAAAA

### ISSUE THREAD

**Issue by ArnyS** [gurnec/btcrecover#196] opened 2017-12-14 15:52 UTC
My blockchain.info payload starts with 21 A symbol. Is it says that something was wrong with encoding padding?

**Comment by gurnec** [comment] 2017-12-16 14:43
Closing as duplicate of #186 (I'm looking at this now).

**Closed by gurnec** 2017-12-16 14:43 UTC
Labels: duplicate
