### ISSUE TITLE
NEED HELP !!! -NO SUPPORTED GPU found

### ISSUE THREAD

**Issue by tor888** [gurnec/btcrecover#83] opened 2017-07-05 08:58 UTC
#Hello. Now I trying to run btcrecover on Win 10 PRO Build 15063.
But have a problem -NO SUPPORTED GPU found and compyte.array.
System have a 2 GTX 1060. Need CUDA for btcrecover?Nvidia driver installed.
pycrypto-2.6.win-amd64-py2.7 installed
python-2.7.13.amd64 installed
Protobuf installed
pywin32-221.win-amd64-py2.7 installed.
pyopencl-2017.2+cl12-cp27-cp27m-win_amd64.whl installed.
http://imgur.com/ZaJgnkk
Maybe need install CUDA toolkit?

Whats wrong ? Need help!

**Comment by tor888** [comment] 2017-07-05 15:13
Maybe need install CUDA toolkit?

**Comment by gurnec** [comment] 2017-07-05 17:08
I suspect either PyOpenCL or Numpy is failing to load.

Could you run these two commands and let me know what they say?
```
C:\Python27\python -c "import numpy; print numpy.__version__"
C:\Python27\python -c "import pyopencl; print pyopencl.version.VERSION_TEXT"
```

**Comment by tor888** [comment] 2017-07-05 17:23
Done.
http://imgur.com/3MYnbWF
More.I use Intel HD 510 and 2GTX 1060 not connect to display.

**Comment by gurnec** [comment] 2017-07-05 17:39
I'm not sure why that library isn't being found... could you please try (re-)installing PyOpenCL?

Re-download it from the link in the [INSTALL doc](https://github.com/gurnec/btcrecover/blob/master/docs/INSTALL.md#windows-gpu-acceleration-for-bitcoin-classicxtcore-armory-or-litecoin-qt) and add `--upgrade --force-reinstall` after `pip install`. So for example, to install the 64-bit version, run this:

    C:\Python27\Scripts\pip install --upgrade --force-reinstall pyopencl-2017.1.1+cl12-cp27-cp27m-win_amd64.whl

**Comment by tor888** [comment] 2017-07-05 17:45
Only pyopencl‑2017.2+cl12‑cp27‑cp27m‑win_amd64.whl version there.
It's ok?not 2017.1.1

**Comment by gurnec** [comment] 2017-07-05 17:55
Hmm... I just gave it a try and I'm getting the same error message as you. I suspect there's a bug in that package, or the package was created incorrectly. I'll look into it a bit later today and open an issue upstream as necessary...

**Comment by tor888** [comment] 2017-07-05 17:56
`C:\Users\r\Downloads>C:\Python27\Scripts\pip install --upgrade --force-reinstall pyopencl-2017.2+cl12-cp27-cp27m-win_amd64.whl
Processing c:\users\r\downloads\pyopencl-2017.2+cl12-cp27-cp27m-win_amd64.whl
Collecting pytest>=2 (from pyopencl==2017.2+cl12)
  Using cached pytest-3.1.3-py2.py3-none-any.whl
Collecting cffi>=1.1.0 (from pyopencl==2017.2+cl12)
  Using cached cffi-1.10.0-cp27-cp27m-win_amd64.whl
Collecting pytools>=2017.2 (from pyopencl==2017.2+cl12)
  Using cached pytools-2017.3.tar.gz
Collecting decorator>=3.2.0 (from pyopencl==2017.2+cl12)
  Using cached decorator-4.0.11-py2.py3-none-any.whl
Collecting appdirs>=1.4.0 (from pyopencl==2017.2+cl12)
  Using cached appdirs-1.4.3-py2.py3-none-any.whl
Collecting six>=1.9.0 (from pyopencl==2017.2+cl12)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting numpy (from pyopencl==2017.2+cl12)
  Using cached numpy-1.13.0-cp27-none-win_amd64.whl
Collecting colorama; sys_platform == "win32" (from pytest>=2->pyopencl==2017.2+cl12)
  Using cached colorama-0.3.9-py2.py3-none-any.whl
Collecting setuptools (from pytest>=2->pyopencl==2017.2+cl12)
  Downloading setuptools-36.0.1-py2.py3-none-any.whl (476kB)
    100% |################################| 481kB 67kB/s
Collecting py>=1.4.33 (from pytest>=2->pyopencl==2017.2+cl12)
  Using cached py-1.4.34-py2.py3-none-any.whl
Collecting pycparser (from cffi>=1.1.0->pyopencl==2017.2+cl12)
  Using cached pycparser-2.18.tar.gz
Installing collected packages: colorama, setuptools, py, pytest, pycparser, cffi, decorator, appdirs, six, numpy, pytools, pyopencl
  Found existing installation: colorama 0.3.9
    Uninstalling colorama-0.3.9:
      Successfully uninstalled colorama-0.3.9
  Found existing installation: setuptools 28.8.0
    Uninstalling setuptools-28.8.0:
      Successfully uninstalled setuptools-28.8.0
  Found existing installation: py 1.4.34
    Uninstalling py-1.4.34:
      Successfully uninstalled py-1.4.34
  Found existing installation: pytest 3.1.3
    Uninstalling pytest-3.1.3:
      Successfully uninstalled pytest-3.1.3
  Found existing installation: pycparser 2.18
    Uninstalling pycparser-2.18:
      Successfully uninstalled pycparser-2.18
  Running setup.py install for pycparser ... done
  Found existing installation: cffi 1.10.0
    Uninstalling cffi-1.10.0:
      Successfully uninstalled cffi-1.10.0
  Found existing installation: decorator 4.0.11
    Uninstalling decorator-4.0.11:
      Successfully uninstalled decorator-4.0.11
  Found existing installation: appdirs 1.4.3
    Uninstalling appdirs-1.4.3:
      Successfully uninstalled appdirs-1.4.3
  Found existing installation: six 1.10.0
    Uninstalling six-1.10.0:
      Successfully uninstalled six-1.10.0
  Found existing installation: numpy 1.13.0
    Uninstalling numpy-1.13.0:
      Successfully uninstalled numpy-1.13.0
  Found existing installation: pytools 2017.3
    Uninstalling pytools-2017.3:
      Successfully uninstalled pytools-2017.3
  Running setup.py install for pytools ... done
  Found existing installation: pyopencl 2017.2+cl12
    Uninstalling pyopencl-2017.2+cl12:
      Successfully uninstalled pyopencl-2017.2+cl12
Successfully installed appdirs-1.4.3 cffi-1.10.0 colorama-0.3.9 decorator-4.0.11 numpy-1.13.0 py-1.4.34 pycparser-2.18 pyopencl-2017.2+cl12 pytest-3.1.3 pytools-2017.3 setuptools-36.0.1 six-1.10.0

C:\Users\r\Downloads>Microsoft Windows [Version 10.0.15063]`

**Comment by tor888** [comment] 2017-07-05 17:59
Many thanx  you very need work. I'll wait and hope I found my password.
Will pay you to BTC address.

**Comment by gurnec** [comment] 2017-07-05 19:26
It looks like the problem is with the PyOpenCL download. I've reached out to the individual who maintains those packages to let him know, hopefully he'll be able to fix them.

In the mean time, you can work around it by following this:

 1. Visit [this GitHub repo](https://github.com/inducer/compyte) and download the ZIP file (big green button on the right).
 2. Extract the zip file, and rename the `compyte-master` folder to `compyte`.
 3. Move the `compyte` folder inside of the `C:\Python27\Lib\site-packages\pyopencl` folder on your PC.

That should be it, but if not please re-run those two `import` commands above and post back the results.

**Comment by tor888** [comment] 2017-07-06 02:19
Yes.! It's work!

**Comment by gurnec** [comment] 2017-07-14 19:43
The PyOpenCL binary package was updated by its maintainer and no longer has this problem, so I'm going to go ahead and close this issue. Feel free to comment if you run into any other issues.

**Closed by gurnec** 2017-07-14 19:43 UTC

**Comment by nori19870522** [comment] 2020-02-01 03:20
I am Japanese and do password analysis.
https://keychainx.io/ 

This is Robert's article.
https://news.bitstarz.com/bitstarz-news-interview-robert-rhodin-keychainx-ceo  

I may be able to find the password you lost. Do you need help with your login?

You can contact us on https://keychainx.io or send mail to help@keychainx.io

**Comment by viladmir2022** [comment] 2021-11-10 10:50
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com
