### ISSUE TITLE
Additional instructions for macOS (python)

### ISSUE THREAD

**Issue by flatr0ze** [gurnec/btcrecover#21] opened 2016-06-26 07:54 UTC
Please add the following information to the existing documentation:

Python on macOS comes without bsddb support, ergo the bsddb3 python module that btcrecover relies upon will complain about the missing _bsddb symbol in that module.
The way to solve this using brew is: `brew install python --with-berkeley-db4`. Then make sure you open a new terminal instance to run the new `python` from the Cellar and not the old `python` (macOS's one).
Or simply exec the binary like this in your console after installation: `$(brew --cellar)/python/2.7.11/bin/python ./btcrecover.py ... ...` (or whichever version/path is related to your OS).

Notes:
May require `brew install berkeley-db4` prior.

References:
 - http://chriszf.posthaven.com/getting-berkeleydb-working-with-python-on-osx
 - http://stackoverflow.com/questions/16003224/installing-bsddb-package-python

**Comment by gurnec** [comment] 2016-06-30 13:58
I actually wrote some code a while back to remove the dependency on the bsddb module by parsing the wallet file itself in pure Python. It was intended for potential [PyPy](http://pypy.org/) support, but there wasn't much (any? I don't recall) performance improvement, so I never merged it to master.

I'm thinking of merging it in. It uses bsddb if it's present, and automatically falls back to using pure Python otherwise. This would make life easier for newbies who aren't familiar with brew.

In any case, I'll update the docs to point here, so thanks a lot for your additional instructions!

**Closed** 2016-07-05 19:30 UTC
Labels: enhancement

**Comment by flatr0ze** [comment] 2016-07-08 08:43
Really good job, thank you for updating and maintaining the repo.
